//=================================================================================
// CONFIGURE REFINE UI ANNOUNCE
// REFINE ANNOUNCE : 0 = DISABLE, 1 = ENABLE
// EQUIPMENT : VALUE REFINE TO ANNOUNCE [0 ~ MAX_REFINE]
// WEAPON LEVEL 1 : VALUE REFINE TO ANNOUNCE [0 ~ MAX_REFINE]
// WEAPON LEVEL 2 : VALUE REFINE TO ANNOUNCE [0 ~ MAX_REFINE]
// WEAPON LEVEL 3 : VALUE REFINE TO ANNOUNCE [0 ~ MAX_REFINE]
// WEAPON LEVEL 4 : VALUE REFINE TO ANNOUNCE [0 ~ MAX_REFINE]
//=================================================================================
refine_announce: 1
equipment: 10
weapon_level_1: 10
weapon_level_2: 10
weapon_level_3: 10
weapon_level_4: 10